[package]
name = "everdrive-test"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[profile.release]
lto = true
strip = true

[dependencies]
byteorder = "1"
enum-iterator = "2"
serialport = "4"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
